sonar.projectKey=notetakingapp
sonar.projectName=NoteTakingApp

sonar.sources=backend,frontend

sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8

# Ignore dependencies
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**